name: Autograding Tests

on:
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        id: test-django
        run: |
          python manage.py test

      - name: Autograding
        id: autograding
        uses: classroom-resources/autograding-python-grader@v1
        with:
          timeout: 1
          max-score: 20
          setup-command: |
            source venv/bin/activate
            python manage.py test
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TEST-DJANGO_RESULTS: "${{steps.autograding.outputs.result}}"
        with:
          runners: autograding
          token: ${{ secrets.GITHUB_TOKEN }}
